apiVersion: v1
kind: ConfigMap
metadata:
  name: n8n-config
  namespace: n8n
  labels:
    app.kubernetes.io/name: n8n
data:
  TZ: Asia/Ho_Chi_Minh
  GENERIC_TIMEZONE: Asia/Ho_Chi_Minh
  N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS: "true"
  N8N_RUNNERS_ENABLED: "true"
  DB_TYPE: postgresdb
  DB_POSTGRESDB_DATABASE: n8n
  DB_POSTGRESDB_SCHEMA: public
  DB_POSTGRESDB_HOST: postgresql-cluster-rw.cnpg.svc
  DB_POSTGRESDB_PORT: "5432"
  DB_POSTGRESDB_USER: postgres
  DB_POSTGRESDB_PASSWORD: postgres