apiVersion: v1
kind: Service
metadata:
  name: n8n-external-service
  namespace: n8n
spec:
  selector:
    app.kubernetes.io/name: n8n
  ports:
    - name: n8n
      protocol: TCP
      nodePort: 30001
      port: 5678
      targetPort: 5678
  type: LoadBalancer