apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-config
  namespace: keycloak
  labels:
    app.kubernetes.io/name: keycloak
data:
  KC_BOOTSTRAP_ADMIN_USERNAME: admin
  KC_BOOTSTRAP_ADMIN_PASSWORD: admin
  KC_PROXY_HEADERS: xforwarded
  KC_HTTP_ENABLED: "true"
  KC_HOSTNAME_STRICT: "false"
  KC_HEALTH_ENABLED: "true"
  KC_CACHE: ispn
  KC_DB_URL_DATABASE: keycloak
  KC_DB_URL_HOST: postgresql-cluster-rw.cnpg.svc
  KC_DB_URL_PORT: "5432"
  KC_DB: postgres
  KC_DB_USERNAME: postgres
  KC_DB_PASSWORD: postgres